# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
    os: ubuntu-24.04
    tools:
        python: "3"
    commands:
        # 1. Install ProperDocs and any required themes/plugins
        - pip install properdocs properdocs_theme_readthedocs properdocs_theme_mkdocs
        # 2. Build the static site using the properdocs executable
        - properdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html
