language: php

php:
  - 5.2
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
matrix:
  allow_failures:
    - php: hhvm

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  ##@todo Remove when support of 5.2 will be dropped
  - phpenv global 5.3
  - composer self-update
  - composer install --prefer-source --dev
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs Classes/ unitTests/ --standard=PSR2 -n --ignore=Classes/PHPExcel/Shared/PCLZip
  ## PHPUnit
  - phpunit -c ./unitTests/

notifications:
  email: false
