site_name: PhpSpreadsheet Documentation
repo_url: https://github.com/PHPOffice/phpspreadsheet
edit_uri: edit/master/docs/

theme: readthedocs
extra_css:
    - extra/extra.css
extra_javascript:
    - extra/extrajs.js
