site_name: PhpSpreadsheet Documentation
#site_url: https://github.com/PHPOffice/phpspreadsheet
repo_url: https://github.com/PHPOffice/phpspreadsheet
#repo_name: PhpSpreadsheet
#edit_uri: edit/master/docs/

theme:
  name: mkdocs
  color_mode: auto               # Options: light, dark, or auto
  user_color_mode_toggle: true    # Adds a button for users to switch manually
extra_css:
    - extra/extra.css
    - extra/copyclipboard.css
extra_javascript:
    - extra/extrajs.js
    - extra/copyclipboard.js
    # Mkdocs theme does not honor green and red color for ✔ and ✖.
    # I am at a loss to explain why, or even how; no other theme has this problem.
    # These are used on features-cross-reference page.
    # The following script converts to thinner versions of those
    # symbols; I'm not sure it's worth it, especially since the
    # thin checkmark is a little difficult to see in dark mode.
    # - extra/nothickcheck.js
markdown_extensions:
    - md_in_html
