<?php

declare(strict_types=1);

namespace PhpOffice\PhpSpreadsheetTests\Reader\Xlsx;

use PhpOffice\PhpSpreadsheet\Reader\Exception;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;
use PhpOffice\PhpSpreadsheet\Shared\Xlsx\AgileEncryption;
use PHPUnit\Framework\TestCase;

class AgileEncryptionTest extends TestCase
{
    private const FIXTURE = 'tests/data/Reader/XLSX/agile-encrypted-excel.xlsx';

    public function testReadExcelAgileEncryptionFixture(): void
    {
        // Generated by Microsoft Excel 16.111.2. Password-to-open: open.
        $reader = new Xlsx();
        $reader->setEncryptionPassword('open');
        $spreadsheet = $reader->load(self::FIXTURE);

        self::assertSame('agile encryption fixture', $spreadsheet->getActiveSheet()->getCell('A1')->getValue());
        self::assertSame(42, $spreadsheet->getActiveSheet()->getCell('B1')->getValue());
        $spreadsheet->disconnectWorksheets();
    }

    public function testListWorksheetMetadataForEncryptedWorkbook(): void
    {
        $reader = (new Xlsx())->setEncryptionPassword('open');

        self::assertSame(['Sheet1'], $reader->listWorksheetNames(self::FIXTURE));
        self::assertSame(
            [[
                'worksheetName' => 'Sheet1',
                'lastColumnLetter' => 'B',
                'lastColumnIndex' => 1,
                'totalRows' => 1,
                'totalColumns' => 2,
                'sheetState' => 'visible',
            ]],
            $reader->listWorksheetInfo(self::FIXTURE)
        );
    }

    public function testEncryptedWorkbookRequiresPassword(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('XLSX encryption password required');
        (new Xlsx())->load(self::FIXTURE);
    }

    public function testEncryptedWorkbookRejectsIncorrectPassword(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('XLSX encryption password is incorrect');
        (new Xlsx())->setEncryptionPassword('wrong')->load(self::FIXTURE);
    }

    public function testRejectsTamperedEncryptedPackage(): void
    {
        $package = AgileEncryption::encrypt("PK\x03\x04test", 'password');
        $package['encryptedPackage'][strlen($package['encryptedPackage']) - 1] = "\x00";

        $this->expectException(Exception::class);
        $this->expectExceptionMessage('integrity check failed');
        AgileEncryption::decrypt(AgileEncryption::parse($package['encryptionInfo']), $package['encryptedPackage'], 'password');
    }

    public function testRejectsUnsupportedEncryptionInfo(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Unsupported XLSX encryption profile');
        AgileEncryption::parse("\x04\x00\x04\x00\x00\x00\x00\x00");
    }

    public function testPasswordDoesNotAffectNormalXlsx(): void
    {
        $reader = (new Xlsx())->setEncryptionPassword('unused');
        $spreadsheet = $reader->load('tests/data/Reader/XLSX/threesheets.xlsx');

        self::assertSame(3, $spreadsheet->getSheetCount());
        $spreadsheet->disconnectWorksheets();
    }

    public function testSupportsApprovedAgileProfiles(): void
    {
        foreach ([[128, 'SHA-1'], [192, 'SHA256'], [256, 'SHA384'], [256, 'SHA512']] as [$keyBits, $hashAlgorithm]) {
            $package = AgileEncryption::encrypt('profile test', 'password', $keyBits, $hashAlgorithm, 10);
            $info = AgileEncryption::parse($package['encryptionInfo']);
            self::assertSame($keyBits, $info['keyBits']);
            self::assertSame($hashAlgorithm, $info['hashAlgorithm']);
            self::assertSame('profile test', AgileEncryption::decrypt($info, $package['encryptedPackage'], 'password'));
        }
    }
}
