<?php

declare(strict_types=1);

namespace PhpOffice\PhpSpreadsheetTests\Reader\Xlsx;

use PhpOffice\PhpSpreadsheet\Reader\Exception;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;
use PhpOffice\PhpSpreadsheet\Shared\Xlsx\AgileEncryption;
use PHPUnit\Framework\TestCase;

class AgileEncryptionTest extends TestCase
{
    private const FIXTURE = 'tests/data/Reader/XLSX/agile-encrypted-excel.xlsx';

    public function testReadExcelAgileEncryptionFixture(): void
    {
        // Generated by Microsoft Excel 16.111.2. Password-to-open: open.
        $reader = new Xlsx();
        $reader->setEncryptionPassword('open');
        $spreadsheet = $reader->load(self::FIXTURE);

        self::assertSame('agile encryption fixture', $spreadsheet->getActiveSheet()->getCell('A1')->getValue());
        self::assertSame(42, $spreadsheet->getActiveSheet()->getCell('B1')->getValue());
        $spreadsheet->disconnectWorksheets();
    }

    public function testCanReadEncryptedWorkbook(): void
    {
        self::assertTrue((new Xlsx())->canRead(self::FIXTURE));
        self::assertFalse((new Xlsx())->canRead('tests/data/Reader/XLS/sample.xls'));
    }

    public function testNonEncryptedOleFallsBackToNormalXlsxLoading(): void
    {
        $this->expectException(Exception::class);
        (new Xlsx())->load('tests/data/Reader/XLS/sample.xls');
    }

    public function testListWorksheetMetadataForEncryptedWorkbook(): void
    {
        $reader = (new Xlsx())->setEncryptionPassword('open');

        self::assertSame(['Sheet1'], $reader->listWorksheetNames(self::FIXTURE));
        self::assertSame(
            [[
                'worksheetName' => 'Sheet1',
                'lastColumnLetter' => 'B',
                'lastColumnIndex' => 1,
                'totalRows' => 1,
                'totalColumns' => 2,
                'sheetState' => 'visible',
            ]],
            $reader->listWorksheetInfo(self::FIXTURE)
        );
    }

    public function testEncryptedWorkbookRequiresPassword(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('XLSX encryption password required');
        (new Xlsx())->load(self::FIXTURE);
    }

    public function testEncryptedWorkbookRejectsIncorrectPassword(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('XLSX encryption password is incorrect');
        (new Xlsx())->setEncryptionPassword('wrong')->load(self::FIXTURE);
    }

    public function testRejectsTamperedEncryptedPackage(): void
    {
        $package = AgileEncryption::encrypt("PK\x03\x04test", 'password');
        $lastByte = strlen($package['encryptedPackage']) - 1;
        $package['encryptedPackage'][$lastByte] = chr(ord($package['encryptedPackage'][$lastByte]) ^ 1);

        $this->expectException(Exception::class);
        $this->expectExceptionMessage('integrity check failed');
        AgileEncryption::decrypt(AgileEncryption::parse($package['encryptionInfo']), $package['encryptedPackage'], 'password');
    }

    public function testRejectsMalformedEncryptedPackage(): void
    {
        $package = AgileEncryption::encrypt('package', 'password', 128, 'SHA-1', 10);

        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Malformed encrypted XLSX package');
        AgileEncryption::decrypt(AgileEncryption::parse($package['encryptionInfo']), substr($package['encryptedPackage'], 0, 7), 'password');
    }

    public function testRejectsMalformedEncryptionInfo(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Malformed XLSX encryption information');
        AgileEncryption::parse("\x04\x00\x04\x00\x40\x00\x00\x00not XML");
    }

    public function testEncryptRequiresSupportedProfileAndPassword(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('XLSX encryption password required');
        AgileEncryption::encrypt('package', '');
    }

    public function testEncryptRejectsUnsupportedProfile(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Unsupported XLSX encryption profile');
        AgileEncryption::encrypt('package', 'password', 64, 'SHA512', 10);
    }

    public function testRejectsUnsupportedEncryptionInfo(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Unsupported XLSX encryption profile');
        AgileEncryption::parse("\x04\x00\x04\x00\x00\x00\x00\x00");
    }

    public function testPasswordDoesNotAffectNormalXlsx(): void
    {
        $reader = (new Xlsx())->setEncryptionPassword('unused');
        $spreadsheet = $reader->load('tests/data/Reader/XLSX/threesheets.xlsx');

        self::assertSame(3, $spreadsheet->getSheetCount());
        $spreadsheet->disconnectWorksheets();
    }

    public function testSupportsApprovedAgileProfiles(): void
    {
        foreach ([[128, 'SHA-1'], [192, 'SHA256'], [256, 'SHA384'], [256, 'SHA512']] as [$keyBits, $hashAlgorithm]) {
            $package = AgileEncryption::encrypt('profile test', 'password', $keyBits, $hashAlgorithm, 10);
            $info = AgileEncryption::parse($package['encryptionInfo']);
            self::assertSame($keyBits, $info['keyBits']);
            self::assertSame($hashAlgorithm, $info['hashAlgorithm']);
            self::assertSame('profile test', AgileEncryption::decrypt($info, $package['encryptedPackage'], 'password'));
        }
    }

    public function testDecryptsMultipleEncryptedSegments(): void
    {
        $plain = str_repeat('x', 4097);
        $package = AgileEncryption::encrypt($plain, 'password', 128, 'SHA-1', 10);

        self::assertSame($plain, AgileEncryption::decrypt(AgileEncryption::parse($package['encryptionInfo']), $package['encryptedPackage'], 'password'));
    }
}
